### ISSUE TITLE
Support Detect Swipe

### ISSUE THREAD

**Issue by simone960** [BWPanda/featherlight#10]
I wonder if you can add detect swipe to the module since this is supported in featherlight module itself and the file can be found in:

https://github.com/noelboss/featherlight/tree/master/assets/javascripts

I actually get it working by:

1) Upload "jquery.detect_swipe.js" file to your "library" folder 

2) and load this file BEFORE the gallery js file in your featherlight.module file. e.g
(ref: https://github.com/noelboss/featherlight/issues/119#issuecomment-78307447)

  ```
$libraries['featherlight-gallery'] = array(
    'title' => 'Featherlight Gallery',
    'website' => 'https://noelboss.github.io/featherlight/gallery.html',
    'version' => '1.7.13',
    'js' => array(
      backdrop_get_path('module', 'featherlight') . '/library/jquery.detect_swipe.js' => array(),
      backdrop_get_path('module', 'featherlight') . '/library/featherlight.gallery.min.js' => array(),
    ),
    'css' => array(
      backdrop_get_path('module', 'featherlight') . '/library/featherlight.gallery.min.css' => array(),
    ),
    'dependencies' => array(
      array('featherlight', 'featherlight'),
    ),
  );
```
I got it working on my mobile. Should be working on other touch screen as well though I haven't tested. The navigation left and right arrows are hidden as designed and you can really swipe the gallery photos smoothly. I am not a module developer, I'm not sure how to implement this properly. It's good you can implement this in this great module in the right way to get this feature supported. So that, next time when I upgrade this module, I do not need to do it again. Please consider. Thank you.

**Comment by ghost** [comment]
Thanks for the suggestion! I have added an option for 'swipe' which will load the detect-swipe library when enabled: https://github.com/backdrop-contrib/featherlight/commit/dacf4350dd86e8d60b1f8c53cd1e05d1f0563f74

And here's a new version that includes this change: https://github.com/backdrop-contrib/featherlight/releases/tag/1.x-1.0.4

**Comment by simone960** [comment]
Thanks @BWPanda!  You are awesome!
