### ISSUE TITLE
Featherlight doesn't work with views

### ISSUE THREAD

**Issue by korontari** [BWPanda/featherlight#3]
I have tried using this lightbox with views but couldn't make it work (Colorbox works well in that situation, so I don't think this is a setup problem). At the same time Featherlight works as expected for a simple page with one or several image fields.

**Comment by ghost** [comment]
Can you please provide an export of your view so I can try to replicate this? When editing your view, click the arrow next to 'Change view name/description' and select 'Export view'. Copy & paste the 'Exported configuration' value into a text file and then attach the file here.

**Comment by korontari** [comment]
Yes, here it is:
[featherlight_view_export.txt](https://github.com/backdrop-contrib/featherlight/files/2563175/featherlight_view_export.txt)

**Comment by ghost** [comment]
Thanks @korontari, I was able to replicate the issue and I'll work on a fix.

**Comment by korontari** [comment]
Thank you! I am interested in having a good responsive and stylish lightbox for a gallery and would gladly help to improve Featherlight.

**Comment by ghost** [comment]
I've made some commits that should fix this. Please try the latest code (no release yet) and let me know if that works for you.

**Comment by korontari** [comment]
I have tested the latest code with various views settings and it works
fine! Thank you for fixing it, Peter.

Do you mind if I post more fixes and feature request to improve the
lightbox? There is an issue with title dispaly and also I have some ideas
of usability and design improvements.

**Comment by ghost** [comment]
Glad to hear. Sure, create a new issue for each bug/idea and I'll look over them when I get a chance.
