### ISSUE TITLE
Interaction on mobile devices

### ISSUE THREAD

**Issue by korontari** [BWPanda/featherlight#8]
Probably this is the last feature suggestion. :) 
I was testing the lightbox on a mobile phone and noticed that arrows are always visible over an image.  On small screens they seem especially large and can hide important details of the image. Also it seem to me that it would be great to simplify UI and user interaction with lightbox on a mobile devices.

So here are some variants as I see it:

1. Ideally it would be to hide arrows on mobile devices and implement swipe gestures: left-right to swithc to next/previous image and up/down to exit lightbox.

2. Another (seemengly simple) soluton would be showing arrows only when user taps the image and then hide them after a short interval of inactivity (say 1 sec or even less).

3. A totally minmalistic approach: arrows are not displayed at all. User taps the image to proceed to the next one in a gallery. No functionality to see previous image is offered (in most cases visitors just click to proceed to next image and rarely try to go back).

I would personally prefer either 1 or 3, as there are no visible controls required.

**Comment by ghost** [comment]
The arrows are provided and styled by the [Featherlight plugin](https://noelboss.github.io/featherlight/) itself. This Backdrop module does not do anything to change them from the default. Therefore I'd suggest either seeing if you can style them differently yourself with CSS, or post your suggestions to the [Featherlight issue queue](https://github.com/noelboss/featherlight/issues).

**Comment by korontari** [comment]
Got it, thank you!
